In [1]:
import numpy as np

In [2]:
stores=np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune" 
])

In [3]:
categories=np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports" 
])

In [4]:
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

In [5]:
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])


In [6]:
print("stores:",stores)
print("Product Categories:",categories)
print("Sales Data:",sales_data)
print("Cost Data:",cost_data)

stores: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']
Product Categories: ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']
Sales Data: [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Cost Data: [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


1.Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.
Write NumPy code to display:
Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array

In [7]:
print("Dimensions:",sales_data.ndim)

Dimensions: 2


In [8]:
print("Shape:",sales_data.shape)

Shape: (5, 6)


In [9]:
print("Total Number of values:",sales_data.size)

Total Number of values: 30


In [10]:
print("Data type of Array:",sales_data.dtype)

Data type of Array: int64


In [14]:
print("Memory occupied by the array:",sales_data.itemsize*sales_data.size)

Memory occupied by the array: 240


2.Store and Category Count
Calculate the following:
Total number of stores
Total number of product categories
Total number of store-category combinations

In [16]:
print("Total Number of stores:",stores.size)
print("Total Number of Product Categories:",categories.size)
print("Total Number of store-category combinations:",stores.size*categories.size)

Total Number of stores: 5
Total Number of Product Categories: 6
Total Number of store-category combinations: 30


3.he reporting application requires sales values in floating-point format.
Convert sales_data into:
float32
float64
Compare the memory used by both arrays.

In [21]:
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
],dtype=np.float32)
print("Memory size for float32:",sales_data.itemsize*sales_data.size)
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
],dtype=np.float64)
print("Memory size for float64:",sales_data.itemsize*sales_data.size)

Memory size for float32: 120
Memory size for float64: 240


Indexing and Data Extraction

4.Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.
Extract and display the complete sales row for Bengaluru.

In [24]:
print(sales_data[0])

[850000. 420000. 310000. 275000. 190000. 225000.]


5.Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories.

In [25]:
print("Total cost incurred by the Mumbai store for all product categories:",cost_data[3].sum())

Total cost incurred by the Mumbai store for all product categories: 2065000


6.Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.
Extract the Electronics sales column from sales_data.

In [26]:
print("Electronics_sales:",sales_data[:,0])

Electronics_sales: [ 850000.  780000.  920000. 1050000.  690000.]


7.Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.

In [27]:
print("The clothing cost for every store:",cost_data[:,2])

The clothing cost for every store: [220000 210000 245000 265000 205000]


8.Hyderabad Furniture Performance
Find the following for Hyderabad:
Furniture sales
Furniture cost
Furniture profit

In [29]:
print("Furniture sales:",sales_data[1,3])
print("Furniture cost:",cost_data[1,3])
print("Furniture Profit:",sales_data[1,3]-cost_data[1,3])

Furniture sales: 310000.0
Furniture cost: 225000
Furniture Profit: 85000.0


9.Chennai Category Range
Extract Chennai’s sales for the following categories:
Groceries
Clothing
Furniture
Use array slicing.

In [30]:
print("Chennai sales:",sales_data[2,1:4])

Chennai sales: [390000. 340000. 260000.]


10.Selected Store Analysis
Extract sales data for:
Bengaluru
Chennai
Pune
Include only:
Electronics
Clothing
Beauty
Use advanced indexing.

In [ ]:
store_indices = np.where(
    np.isin(stores, ["Bengaluru", "Chennai", "Pune"])
)[0]
category_indices = np.where(
    np.isin(categories, ["Electronics", "Clothing", "Beauty"])
)[0]
result = sales_data[np.ix_(store_indices, category_indices)]
print(result)

[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


11.Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.

In [52]:
print("total sales revenue generated by all stores and all categories:",sales_data.sum())

total sales revenue generated by all stores and all categories: 11675000.0


12.Calculate total sales revenue for each store.
Display the result together with the store names.

In [54]:
print("Bengaluru:",sales_data[0].sum())
print("Hyderabad:",sales_data[1].sum())
print("Chennai:",sales_data[2].sum())
print("Mumbai:",sales_data[3].sum())
print("Pune:",sales_data[4].sum())


Bengaluru: 2270000.0
Hyderabad: 2295000.0
Chennai: 2310000.0
Mumbai: 2820000.0
Pune: 1980000.0


13.Category-Wise Sales
Calculate total sales for each product category across all stores.
Display each category name with its total sales.

In [55]:
print("Electronics:",sales_data[:,0].sum())
print("Groceries:",sales_data[:,1].sum())
print("Clothing:",sales_data[:,2].sum())
print("Furniture:",sales_data[:,3].sum())
print("Beauty:",sales_data[:,4].sum())
print("Sports:",sales_data[:,5].sum())


Electronics: 4290000.0
Groceries: 2185000.0
Clothing: 1600000.0
Furniture: 1415000.0
Beauty: 1010000.0
Sports: 1175000.0


14.Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.

In [58]:
print("Average sales generated by each store across all six product categories:",np.mean(sales_data,axis=1))

Average sales generated by each store across all six product categories: [378333.33333333 382500.         385000.         470000.
 330000.        ]


15.Average Sales Per Category
Calculate the average sales of each product category across the five stores.

In [59]:
print("The average sales of each product category across the five stores:",np.mean(sales_data,axis=0))

The average sales of each product category across the five stores: [858000. 437000. 320000. 283000. 202000. 235000.]


16.Highest-Selling Store
Identify:
Index of the store with the highest total sales
Name of the store
Total sales generated by that store

In [77]:
result=np.argmax(sales_data.sum(axis=1))
print(stores[result],":",sales_data[result].sum())

Mumbai : 2820000.0


Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.
Use np.argmin().

In [1]:
import numpy as np

In [7]:
result=np.argmin(sales_data.sum(axis=1))
print(stores[result],":",sales_data[result].sum())

Pune : 1980000


18.Highest-Selling Category
Find the product category that generated the highest total sales across the company.

In [12]:
result=np.argmax(sales_data.sum(axis=0))
print(categories[result],":",sales_data[:,result].sum())

Electronics : 4290000


19.Lowest-Selling Category
Find the product category with the lowest total sales across all stores.

In [16]:
result=np.argmin(sales_data.sum(axis=0))
print(categories[result],":",sales_data[:,result].sum())

Beauty : 1010000


Cost Analysis

20.Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories.

In [17]:
print("The total cost incurred by smartmart across all stores and product categories:",cost_data.sum())

The total cost incurred by smartmart across all stores and product categories: 8600000


21.Store-Wise Cost
Calculate the total cost incurred by each store.

In [18]:
print("The total cost incurred by each store:",cost_data.sum(axis=1))

The total cost incurred by each store: [1665000 1685000 1710000 2065000 1475000]


22.Category-Wise Cost
Calculate the total cost incurred for each product category across all stores.

In [19]:
print("The total cost incurred for each product category across all stores:",cost_data.sum(axis=0))

The total cost incurred for each product category across all stores: [3250000 1660000 1145000 1045000  665000  835000]


23.Most Expensive Store
Identify the store with the highest total operating cost.

In [24]:
result=np.argmax(cost_data.sum(axis=1))
print(stores[result],":",cost_data[result].sum())

Mumbai : 2065000


24.Lowest-Cost Store
Identify the store with the lowest total cost.

In [29]:
result=np.argmin(cost_data.sum(axis=1))
print(stores[result],":",cost_data[result].sum())

Pune : 1475000


25.Most Expensive Product Category
Determine which product category has the highest total cost across all stores.

In [33]:
result=np.argmax(cost_data.sum(axis=0))
print(categories[result],":",cost_data[:,result].sum())

Electronics : 3250000


Profit Analysis Using Two Arrays

26.Profit Matrix
Calculate the profit generated for every store and product category.

In [6]:
profit_data=sales_data-cost_data
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


27.Store-Wise Profit
Calculate the total profit generated by each store.

In [7]:
result=profit_data.sum(axis=1)
print(result)

[605000 610000 600000 755000 505000]


28.Category-Wise Profit
Calculate the total profit generated by each product category.

In [8]:
result=profit_data.sum(axis=0)
print(result)

[1040000  525000  455000  370000  345000  340000]


29.Most Profitable Store
Identify the store that generated the highest total profit.
Display:
Store name
Total sales
Total cost
Total profit

In [11]:
result=np.argmax(profit_data.sum(axis=1))
print("Store name:",stores[result])
print("Total Sales:",sales_data[result].sum())
print("Total Cost:",cost_data[result].sum())
print("Total Profit:",profit_data[result].sum())

Store name: Mumbai
Total Sales: 2820000
Total Cost: 2065000
Total Profit: 755000


30.Least Profitable Store
Identify the store that generated the lowest total profit.

In [14]:
result=np.argmin(profit_data.sum(axis=1))
print("Store:",stores[result])

Store: Pune


31.Most Profitable Category
Find the category with the highest total profit across all stores.

In [17]:
result=np.argmax(profit_data.sum(axis=0))
print("Category:",categories[result])

Category: Electronics


32.Least Profitable Category
Find the category with the lowest total profit.

In [22]:
result=np.argmin(profit_data.sum(axis=0))
print("Categories:",categories[result])

Categories: Sports


33.Maximum Individual Profit
Find the highest profit generated by any single store-category combination.
Display:
Profit amount
Store name
Product category

In [341]:
max_index = np.argmax(profit_data)
row, column = np.unravel_index(max_index, profit_data.shape)
print("Profit Amount:", profit_data[row, column])
print("Store:", stores[row])
print("Category:", categories[column])

Profit Amount: 260000
Store: Mumbai
Category: Electronics


34.Minimum Individual Profit
Find the smallest profit generated by a store-category combination.
Display the corresponding store and category.

In [342]:
min_index = np.argmin(profit_data)
row, column = np.unravel_index(min_index, profit_data.shape)
print("Profit Amount:", profit_data[row, column])
print("Store:", stores[row])
print("Category:", categories[column])

Profit Amount: 55000
Store: Pune
Category: Furniture


Profit Margin analysis

35.Profit Margin Matrix
Calculate the profit margin percentage for every store-category combination.

In [7]:
profit_margin1=(profit_data/sales_data)*100
profit_margin=np.round(profit_margin1,2)
print(profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


36.Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:

In [43]:
Total_Store_Profit=profit_margin.sum(axis=1)
Total_Store_sales=sales_data.sum(axis=1)
Store_Profit_margin=(Total_Store_Profit/Total_Store_sales)*100
print(Store_Profit_margin)


[0.0073696  0.00727669 0.00711082 0.00597411 0.00815354]


37.Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.

In [44]:
result=profit_margin.sum(axis=0)
print(result)

[120.93 120.26 141.9  129.85 170.97 144.55]


38.Best Store by Profit Margin
Identify the store with the highest overall profit margin.

In [47]:
result=np.argmax(profit_margin.sum(axis=1))
print(stores[result])

Mumbai


39.Best Category by Profit Margin
Identify the product category with the highest profit margin.

In [50]:
result=np.argmax(profit_margin.sum(axis=0))
print(categories[result])

Beauty


40.Management considers a profit margin below 22% to be weak.
Find all store-category combinations where the profit margin is below 22%.
Display:
Store
Category
Sales
Cost
Profit
Profit margin

In [54]:
print(np.where(profit_margin < 22))

(array([], dtype=int64), array([], dtype=int64))


Boolean Filtering

41.High Sales Values
Find all sales values greater than ₹5,00,000.

In [57]:
result=sales_data > 500000
print(sales_data[result])

[ 850000  780000  920000 1050000  510000  690000]


42.Low Sales Values
Find all sales values below ₹2,00,000.

In [59]:
result=sales_data<200000
print(sales_data[result])

[190000 185000 175000]


43.High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.

In [63]:
result=np.greater(profit_data,150000)
print(profit_data[result])

[210000 190000 220000 260000 160000]


44.Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.

In [65]:
result=np.logical_and(sales_data>=250000,sales_data<=500000)
print(sales_data[result])

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


45.Premium Performance
A store-category combination is considered premium when:
Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations.

In [68]:
result=np.logical_and(sales_data >500000,profit_data>150000)
print(result)

[[ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]]


46.Underperforming Combinations
A store-category combination is considered underperforming when:
Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.

In [69]:
result=np.logical_and(sales_data>250000,profit_margin<25)
print(result)

[[ True False False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]]


47.Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().

In [71]:
result=np.where(
    sales_data>=500000,"High",
    np.where(sales_data>=250000,"Medium","Low")
)
print(result)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


Target-Based Analysis

In [34]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

48.Target Comparison
Compare every store’s category sales against sales_targets.
Use NumPy broadcasting.

In [75]:
result=(sales_data==sales_targets)
print(result)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


49.Target Achievement Matrix
Create a Boolean array where:
True means the store achieved the category target
False means the store failed to achieve the target

In [44]:
result=(sales_data>=sales_targets)
print(result)


[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


50.Target Achievement Count
Calculate the number of categories in which each store achieved its target.

In [45]:
print(np.sum(sales_data>=sales_targets))

13


51.Best Target-Performing Store
Find the store that achieved the highest number of category targets.

In [339]:
target_achievement = sales_data >= sales_targets
target_count = np.sum(target_achievement, axis=1)
best_store_index = np.argmax(target_count)
print("Best Store:", stores[best_store_index])
print("Number of Targets Achieved:", target_count[best_store_index])

Best Store: Mumbai
Number of Targets Achieved: 6


52.Target Achievement by Category
Calculate how many stores achieved the target for each product category

In [340]:
target_achievement = sales_data >= sales_targets
category_target_count = np.sum(target_achievement, axis=0)
print(category_target_count)

[3 2 2 2 2 2]


53.Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

In [79]:
variance=sales_data-sales_targets
print(variance)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


54.Percentage Above or Below Target
Calculate the percentage variance from the target using:

In [80]:
variance_percentage=((sales_data-sales_targets)/sales_targets)*100
print(variance_percentage)

[[  6.25        -6.66666667  -3.125       -8.33333333  -5.
   -2.17391304]
 [ -2.5          2.22222222  -7.8125       3.33333333   5.
    4.34782609]
 [ 15.         -13.33333333   6.25       -13.33333333  -7.5
   -6.52173913]
 [ 31.25        13.33333333  17.1875      15.          25.
   26.08695652]
 [-13.75       -10.         -12.5        -25.         -12.5
  -10.86956522]]


55.Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.

In [86]:
result=(sales_data[:,0]==sales_targets[0])
count=0
for i in result:
    if(i==False):
        print(stores[count])
        count=count+1
    else:
        count=count+1

Bengaluru
Hyderabad
Chennai
Mumbai
Pune


56.Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

In [88]:
print(np.all(sales_data==sales_targets))

False


57.Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

In [89]:
print(np.any(sales_data==sales_targets))

False


Discount Scenario

In [8]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

58.Discount Amount Matrix
Calculate the discount amount for each store-category combination.

In [9]:
discount=np.multiply(sales_data,discount_rates)
print(discount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


59.Sales After Discount
Calculate the net sales value after applying the category-wise discounts.

In [96]:
sales=sales_data-discount
print(sales) 

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


60.Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

profit_data=sales-cost
profit_margin%=(profit_data/sales_data)*100

In [97]:
profit_dis_data=sales-cost_data
print(profit_dis_data)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


61.Profit Margin After Discount
Calculate the new profit margin after applying discounts.

In [98]:
profit_dis_margin=(profit_dis_data/sales)
print(profit_dis_margin)

[[0.16339869 0.21052632 0.16508539 0.15289256 0.28489703 0.20987654]
 [0.15954416 0.19908467 0.16251246 0.17521994 0.27536232 0.21296296]
 [0.15458937 0.20377868 0.15224913 0.14772727 0.29494712 0.19896641]
 [0.16402116 0.19504644 0.16862745 0.17654809 0.2826087  0.21455939]
 [0.14653784 0.194282   0.13865546 0.14141414 0.28571429 0.21409214]]


62.Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.
Display the affected store and category names.

In [100]:
print(np.sum(sales<cost_data))

0


63.Discount Impact
Calculate how much total revenue the company loses because of the proposed discounts.

In [101]:
print(discount.sum())

1146350.0


64.Store Most Affected by Discounts
Identify the store that loses the highest amount of revenue due to discounts.

In [104]:
result=np.argmax(discount.sum(axis=1))
print(stores[result])

Mumbai


Tax and Price Adjustment

In [10]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

65.Tax Collection Matrix
Calculate the tax collected on sales for each store and category.

In [11]:
tax=np.multiply(sales_data,tax_rates)
print(tax)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


66. Sales Including Tax
Calculate the final customer billing value after adding tax.

In [113]:
tax_sales=np.add(sales_data,tax)
print(tax_sales)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


67.Store-Wise Tax Collection
Calculate the total tax collected by each store.

In [114]:
tax_store=tax.sum(axis=1)
print("The total tax collected by each store:",tax_store)

The total tax collected by each store: [321900. 321200. 331800. 401400. 274650.]


68.Category-Wise Tax Collection
Calculate total tax collected for each category.

In [115]:
tax_category=tax.sum(axis=0)
print(tax_category)

[772200. 109250. 192000. 254700. 181800. 141000.]


69.Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.

In [118]:
high_tax_store=np.argmax(tax.sum(axis=1))
print(stores[high_tax_store])

Mumbai


Array Modification

70.Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.
Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.
Make the change in a copied array without modifying the original array.

In [122]:
pune_sales=sales_data.copy()
pune_sales[4,0]=740000
print(pune_sales)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


In [132]:
print(sales_data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


71.Revised Beauty Cost
Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.
Create an updated cost array.

In [137]:
update_cost_data=cost_data
update_cost_data[:,4]=update_cost_data[:,4]-(update_cost_data[:,4])*0.08
print(update_cost_data)

[[640000 315000 220000 229600 105800 160000]
 [590000 350000 210000 252000 118496 170000]
 [700000 295000 245000 218400 101568 155000]
 [790000 390000 265000 280000 139656 205000]
 [530000 310000 205000 190400  97336 145000]]


72.Furniture Cost Increase
Furniture costs increase by 12% for all stores.
Update only the Furniture column.

In [138]:
cost_data[:,3]=cost_data[:,3]+(cost_data[:,3]*0.12)
print(cost_data)

[[640000 315000 220000 257152 105800 160000]
 [590000 350000 210000 282240 118496 170000]
 [700000 295000 245000 244608 101568 155000]
 [790000 390000 265000 313600 139656 205000]
 [530000 310000 205000 213248  97336 145000]]


73.Store Closure Simulation
Assume the Pune store is temporarily closed.
Remove Pune’s sales and cost data from the analysis using np.delete().

In [141]:
sales_data1=np.delete(sales_data,4,axis=0)
print(sales_data1)
cost_data1=np.delete(cost_data,4,axis=0)
print(cost_data1)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
[[640000 315000 220000 257152 105800 160000]
 [590000 350000 210000 282240 118496 170000]
 [700000 295000 245000 244608 101568 155000]
 [790000 390000 265000 313600 139656 205000]]


74.Adding a New Store
A new Delhi Store is opened with the following data

In [142]:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])


In [143]:
delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

In [145]:
new_sales_data=np.vstack((sales_data,delhi_sales))
print(new_sales_data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]


In [146]:
new_cost_data=np.vstack((cost_data,delhi_cost))
print(new_cost_data)

[[640000 315000 220000 257152 105800 160000]
 [590000 350000 210000 282240 118496 170000]
 [700000 295000 245000 244608 101568 155000]
 [790000 390000 265000 313600 139656 205000]
 [530000 310000 205000 213248  97336 145000]
 [665000 360000 235000 215000 145000 180000]]


In [153]:
a="Delhi" 
new_stores=np.append(stores,a)
print(new_stores)

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


75.Adding a New Product Category

In [155]:
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

In [160]:
new_sales_appliance=np.column_stack((sales_data,home_appliance_sales))
print(new_sales_appliance)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]


In [161]:
home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

In [162]:
new_cost_appliance=np.column_stack((cost_data,home_appliance_cost))
print(new_cost_appliance)

[[640000 315000 220000 257152 105800 160000 265000]
 [590000 350000 210000 282240 118496 170000 240000]
 [700000 295000 245000 244608 101568 155000 285000]
 [790000 390000 265000 313600 139656 205000 305000]
 [530000 310000 205000 213248  97336 145000 225000]]


Sorting and Ranking

76.Sort Stores by Sales
Sort stores in ascending order based on total sales.
Display store names and sales totals.

In [170]:
result=np.argsort(sales_data.sum(axis=1))
for i in result:
    print(stores[i],":",sales_data[i].sum())

Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000


In [171]:
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


77.Rank Stores by Profit
Rank stores from highest to lowest total profit.

In [173]:
result=np.argsort(profit_data.sum(axis=1))
print(result)

[4 2 0 1 3]


78. Sort Categories by Revenue
Sort product categories from highest to lowest total revenue.

In [178]:
result=sales_data.sum(axis=0)
result1=np.sort(result)[::-1]
sort1=np.argsort(result1)
print(sort1)

[5 4 3 2 1 0]


79.Find the three highest individual sales values in the complete sales matrix.
Display their:
Sales value
Store name
Category name

In [337]:
flat = sales_data.flatten()
top3_indices = np.argsort(flat)[-3:][::-1]
rows, cols = np.unravel_index(top3_indices, sales_data.shape)
for r, c in zip(rows, cols):
    print("Sales:", sales_data[r, c])
    print("Store:", stores[r])
    print("Category:", categories[c])
    print()

Sales: 1050000
Store: Mumbai
Category: Electronics

Sales: 920000
Store: Chennai
Category: Electronics

Sales: 850000
Store: Bengaluru
Category: Electronics



80. Bottom Three Profits
Find the three lowest profit values in the profit matrix.

In [338]:
flat = sales_data.flatten()
bottom3_indices = np.argsort(flat)[:3]
rows, cols = np.unravel_index(bottom3_indices, sales_data.shape)
for r, c in zip(rows, cols):
    print("Sales:", sales_data[r, c])
    print("Store:", stores[r])
    print("Category:", categories[c])
    print()

Sales: 175000
Store: Pune
Category: Beauty

Sales: 185000
Store: Chennai
Category: Beauty

Sales: 190000
Store: Bengaluru
Category: Beauty



Statistical Analysis

81.Calculate the following for the complete sales array:
Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile

In [181]:
print("Maximum:",np.max(sales_data))
print("Minimum:",np.min(sales_data))
print("Mean:",np.mean(sales_data))
print("Median:",np.median(sales_data))
print("Standard Deviation:",np.std(sales_data))
print("Variance:",np.var(sales_data))
print("25th Percentile:",np.percentile(sales_data,25))
print("50th Percentile:",np.percentile(sales_data,50))
print("75th Percentile:",np.percentile(sales_data,75))

Maximum: 1050000
Minimum: 175000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


82.Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

In [182]:
result=np.std(sales_data,axis=1)
print(result)

[223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]


83.Category-Wise Standard Deviation

In [183]:
result=np.std(sales_data,axis=0)
print(result)

[122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]


84.Sales Above Company Average
Calculate the company-wide average sales value.
Count how many store-category sales values are above this average.

In [188]:
result=np.mean(sales_data)
result1=np.greater(sales_data,result)
print((result1.sum()))

10


85.Outlier Detection
Treat any sales value greater than:
Mean + 1.5 × Standard Deviation
as a high-value outlier.
Identify all such sales values.

In [190]:
outlier=np.mean(sales_data)+1.5*np.std(sales_data)
result=np.greater(sales_data,outlier)
print(sales_data[result])

[ 850000  780000  920000 1050000]


Reshaping and Transformation

86. Flatten Sales Data
Convert the two-dimensional sales array into a one-dimensional array using:
flatten()
ravel()
Explain the difference between the two methods.

In [193]:
result=sales_data.flatten()
print(result)

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [194]:
result1=sales_data.ravel()
print(result1)

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


flatten()->The original array is unchanged because Flatten() returns a copy
ravel()->Changes made through the result may effect the original array.

87.Reshape Sales Data
Reshape the 5 × 6 sales array into:
3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.

In [200]:
result=np.reshape(sales_data,(3,10))
print(result)
print("Original Size",sales_data.size)
print("Reshaping Size",result.size)

[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
Original Size 30
Reshaping Size 30


In [201]:
result=np.reshape(sales_data,(10,3))
print(result)
print("Original Size",sales_data.size)
print("Reshaping Size",result.size)

[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
Original Size 30
Reshaping Size 30


In [202]:
result=np.reshape(sales_data,(2,15))
print(result)
print("Original Size",sales_data.size)
print("Reshaping Size",result.size)

[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
Original Size 30
Reshaping Size 30


In [203]:
result=np.reshape(sales_data,(15,2))
print(result)
print("Original Size",sales_data.size)
print("Reshaping Size",result.size)

[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  510000]
 [ 375000  345000]
 [ 250000  290000]
 [ 690000  405000]
 [ 280000  225000]
 [ 175000  205000]]
Original Size 30
Reshaping Size 30


88.Transpose Sales Data
Transpose the sales array so that:
Rows represent product categories
Columns represent stores
Display the new shape.

In [207]:
result=np.transpose(sales_data)
print(result.shape)

(6, 5)


89.Combined Sales and Cost Array
Stack sales_data and cost_data vertically.
Display the resulting shape.

In [209]:
result=np.vstack((sales_data,cost_data))
print(result.shape)

(10, 6)


90.Store-Level Combined Data
Create a three-dimensional array where:
First layer contains sales data
Second layer contains cost data
Display the shape of the new array.

In [214]:
result=np.stack((sales_data,cost_data))
print(result.shape)

(2, 5, 6)


Missing Data Scenario

In [12]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [238]:
sales_with_missing1=sales_with_missing.copy()
print(sales_with_missing1)

[[ 850000.  420000.      nan  275000.  190000.  225000.]
 [ 780000.  460000.  295000.      nan  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.      nan  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.      nan  205000.]]


91.Missing Value Detection
Find:
Total number of missing values
Location of missing values
Stores and categories containing missing values

In [217]:
result=np.isnan(sales_with_missing).sum()
print(result)

4


Location of missing values

In [234]:
result=np.where(np.isnan(sales_with_missing))
print("Location of missing values:",result)
i,j=result


Location of missing values: (array([0, 1, 3, 4]), array([2, 3, 1, 4]))


In [233]:
for r, c in zip(i,j):
    print( stores[r],":",categories[c])

Bengaluru : Clothing
Hyderabad : Furniture
Mumbai : Groceries
Pune : Beauty


92.Replace Missing Values with Zero
Replace all missing sales values with zero.

In [239]:
sales_with_missing1[np.isnan(sales_with_missing1)]=0
print(sales_with_missing1)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


93.Replace with Company Average
Replace missing values with the overall average of available sales values.
Use np.nanmean().

In [244]:
sales_with_missing2=sales_with_missing.copy()
result=np.nanmean(sales_with_missing1)
sales_with_missing2[np.isnan(sales_with_missing2)]=result
print(sales_with_missing2)

[[ 850000.          420000.          345666.66666667  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          345666.66666667
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          345666.66666667  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   345666.66666667  205000.        ]]


94.Replace with Category Average
Replace each missing value with the average sales value of its respective product category.

In [251]:
sales_with_missing3=sales_with_missing.copy()
media=np.nanmean(sales_with_missing3,axis=0)
print(media)
for i in range(sales_with_missing3.shape[1]):
    sales_with_missing3[np.isnan(sales_with_missing3[:,i]),i]=media[i]
print(sales_with_missing3)

[858000. 418750. 322500. 276250. 208750. 235000.]
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


95.Missing Value Impact
Compare total sales before and after replacing missing values with zero.

Before replacing the zero

In [252]:
print("Total Sales Before replacing Zero:",np.nansum(sales_with_missing))

Total Sales Before replacing Zero: 10370000.0


In [254]:
print("Total sales After replacing Zero:",sales_with_missing1.sum())

Total sales After replacing Zero: 10370000.0


Conditional Bussiness Decisions

96.Store Performance Labels
Classify each store based on total sales:
"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000


In [56]:
sales_store=sales_data.sum(axis=1)
conditions=[
    sales_store > 2800000,
    sales_store >= 2400000,
]
choices=[
    "Excellent",
    "Good",
]
result=np.select(conditions,choices,default="Needs Improvement")
print(result)

['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Excellent'
 'Needs Improvement']


97.Profitability Classification
Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero

In [262]:
conditions=[
    sales_data > 200000,
    sales_data >=100000,
    sales_data < 100000
]
choices=[
    "Highly Profitable",
    "Profitable",
    "Low Profit"
]
result=np.select(conditions,choices,default="Loss") 
print(result)

[['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Highly Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Highly Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Profitable' 'Highly Profitable']]


98.Expansion Recommendation
A store is eligible for expansion when:
Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores.

In [269]:
profit=profit_data.sum(axis=1)
profit_m1=profit_margin.sum(axis=1)
result=np.logical_and(sales_store > 2500000,profit > 700000,profit_m1 > 25)
print(result)

[False False False  True False]


99.Category Promotion Recommendation
A product category should receive additional promotion when:
Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.

In [270]:
sales_category=np.mean(sales_data,axis=0)
profit_category=profit_margin.sum(axis=0)
result=np.logical_and(sales_category>300000,profit_category)
print(result)

[ True  True  True False False False]


100.Cost Optimization Recommendation
Find store-category combinations where:
Cost is greater than ₹2,50,000
Profit margin is below 25%
These combinations should be reviewed for cost optimization.

In [271]:
result=np.logical_and(cost_data > 250000,profit_margin < 25)
print(result)

[[ True False False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]]


Inventory Scenario

In [13]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])


In [14]:
units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

101:Closing Stock
Calculate closing stock using:

In [15]:
closing_Stock=opening_stock-units_sold
print(closing_Stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


102.Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units.

In [277]:
result=(closing_Stock < 30)
print(closing_Stock[result])

[25 25 25 25 25 25 25 25 20]


103.Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.

In [278]:
percentage_unsold=((opening_stock-units_sold)/opening_stock)*100
print(percentage_unsold)

[[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


104. Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.
Identify fast-moving store-category combinations.

In [279]:
fast_moving=(units_sold/opening_stock)*100
result=np.where(fast_moving > 80)
print(result)

(array([0, 1, 1, 2, 2, 2, 3, 3, 3, 4]), array([1, 1, 2, 0, 1, 2, 0, 1, 2, 1]))


105. Category-Wise Units Sold
Calculate the total units sold for each product category.

In [280]:
result=units_sold.sum(axis=0)
print(result)

[ 485 1950 1240  345  980  720]


106.Store-Wise Units Sold
Calculate total units sold by each store.

In [281]:
result=units_sold.sum(axis=1)
print(result)

[1110 1175 1095 1390  950]


107.Best Store by Unit Sales
Identify the store that sold the highest total number of units.

In [284]:
result=np.argmax(units_sold.sum(axis=1))
print(stores[result])

Mumbai


108.Reorder Requirement
A store should reorder a category when closing stock is below 25 units.
Create a Boolean reorder matrix.

In [286]:
result=(closing_Stock < 25)
print(result)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


109.Reorder Quantity
Assume each category must maintain 100 units after reordering.
Calculate reorder quantities only for combinations where closing stock is below 25.
For all other combinations, return zero.

In [287]:
reorder_quantity=np.where(
    closing_Stock < 25,
    100-closing_Stock,
    0
)
print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Cumulative Store Sales

110.Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().

In [288]:
result=np.cumsum(sales_data,axis=1)
print(result)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


111.Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.

In [291]:
result=sales_data.flatten()
print(np.cumsum(result))

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


112.Calculate the difference between consecutive category sales for each store 

In [300]:
result=np.diff(sales_data)
print(result)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


113. Unique Sales Values
Find all unique sales values in sales_data.
Also count the frequency of each value.

In [302]:
print(sales_data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [301]:
result=np.unique_values(sales_data)
print(result)

[ 190000  345000  850000  275000  310000  420000  780000  225000  460000
  240000  295000  510000  210000  920000  390000  340000  260000  405000
  290000  185000  215000  250000 1050000  375000  690000  280000  175000
  205000]


In [307]:
result1=np.unique_counts(sales_data)
print(result1)

UniqueCountsResult(values=array([ 175000,  185000,  190000,  205000,  210000,  215000,  225000,
        240000,  250000,  260000,  275000,  280000,  290000,  295000,
        310000,  340000,  345000,  375000,  390000,  405000,  420000,
        460000,  510000,  690000,  780000,  850000,  920000, 1050000]), counts=array([1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1]))


114.Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.
Return its location.

In [308]:
result=np.where(sales_data==420000)
print(result)

(array([0]), array([1]))


115.Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.
Verify whether all combinations are profitable using np.all().

In [310]:
result=np.all(sales_data > cost_data)
print(result)

True


116.Clip Profit Values
For reporting purposes, management wants profit values limited to:
Minimum: ₹75,000
Maximum: ₹2,50,000

In [311]:
result=np.clip(profit_data,75000,250000)
print(result)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


117. Normalize Sales Data
Normalize all sales values using min-max normalization

In [314]:
minimum_sale=np.min(sales_data)
print(minimum_sale)
maximum_sale=np.max(sales_data)
Normalized_sales=((sales_data-minimum_sale)/(maximum_sale-minimum_sale))
print(Normalized_sales)

175000
[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


118.Standardize Sales Data

In [317]:
standardized_sales=(sales_data-np.mean(sales_data))/np.std(sales_data)
print(standardized_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


119. Round Values
Convert profit margin values into:
Two decimal places
Nearest whole number
Floor values
Ceiling values

In [320]:
print(profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [322]:
print(np.round(profit_margin))

[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]


In [323]:
print(np.floor(profit_margin1))

[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]


In [324]:
print(np.ceil(profit_margin1))

[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


120.Save the following arrays as NumPy binary files:
sales_data.npy
cost_data.npy
profit_data.npy

In [330]:
np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("profit_data.npy",profit_data)


In [334]:
np.load("sales_data.npy")

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000]])

In [335]:
np.load("cost_data.npy")

array([[640000, 315000, 220000, 257152, 105800, 160000],
       [590000, 350000, 210000, 282240, 118496, 170000],
       [700000, 295000, 245000, 244608, 101568, 155000],
       [790000, 390000, 265000, 313600, 139656, 205000],
       [530000, 310000, 205000, 213248,  97336, 145000]])

In [336]:
np.load("profit_data.npy")

array([[210000, 105000,  90000,  70000,  65000,  65000],
       [190000, 110000,  85000,  85000,  70000,  70000],
       [220000,  95000,  95000,  65000,  65000,  60000],
       [260000, 120000, 110000,  95000,  85000,  85000],
       [160000,  95000,  75000,  55000,  60000,  60000]])

Final Retail Analytics Project

Company Summary

1.total Company Sales

In [17]:
print("Total Company Sales:",sales_data.sum())

Total Company Sales: 11675000


2.Total company cost

In [18]:
print("Total Company Cost:",cost_data.sum())

Total Company Cost: 8600000


3.Total Comapny Profit

In [20]:
print("Total Company Profit:",profit_data.sum())

Total Company Profit: 3075000


4.Overall Company profit margin

In [24]:
print("Overall Company Profit Margin:",profit_margin1.sum())

Overall Company Profit Margin: 828.4529274527509


5.Average Transaction value

In [25]:
print("Average Transaction value:",np.mean(sales_data))

Average Transaction value: 389166.6666666667


6.Highest Individual sales value

In [27]:
print("Highest Individual Sales Value:",np.max(sales_data))

Highest Individual Sales Value: 1050000


7.Lowest individual sales value

In [28]:
print("Lowest Individual Sales Value:",np.min(sales_data))

Lowest Individual Sales Value: 175000


Store Summary

1.Total Sales

In [29]:
print(sales_data.sum(axis=1))

[2270000 2295000 2310000 2820000 1980000]


2.Total Cost

In [30]:
print(cost_data.sum(axis=1))

[1665000 1685000 1710000 2065000 1475000]


3.Total Profit

In [31]:
print(profit_data.sum(axis=1))

[605000 610000 600000 755000 505000]


4.Profit Margin

In [43]:
print(profit_margin1.sum(axis=1))

[167.29210108 167.004932   164.25530619 168.47122657 161.42936162]


5.Number of category targets achieved

In [54]:
target=sales_data>sales_targets
store_wise=np.sum(target,axis=1)
print(store_wise)

[1 4 2 6 0]


6.Total units sold

In [55]:
print(units_sold.sum(axis=1))

[1110 1175 1095 1390  950]


7.Expansion Eligibility

In [77]:
profit=profit_data.sum(axis=1)
profit_m1=profit_margin.sum(axis=1)
result=np.logical_and(sales_store > 2500000,profit > 700000,profit_m1 > 25)
print(stores[result])

['Mumbai']


Category Summary

1.Total Sales

In [58]:
print(sales_data.sum(axis=0))

[4290000 2185000 1600000 1415000 1010000 1175000]


2.Total Cost

In [59]:
print(cost_data.sum(axis=0))

[3250000 1660000 1145000 1045000  665000  835000]


3.Total Profit

In [60]:
print(profit_data.sum(axis=0))

[1040000  525000  455000  370000  345000  340000]


4.Profit Margin

In [61]:
print(profit_margin.sum(axis=0))

[120.93 120.26 141.9  129.85 170.97 144.55]


5.Average Sales

In [62]:
print(np.mean((sales_data),axis=0))

[858000. 437000. 320000. 283000. 202000. 235000.]


6.Number of stores achieving the target

In [63]:
target=sales_data>sales_targets
store_wise=np.sum(target,axis=0)
print(store_wise)

[3 2 2 2 2 2]


7.Total units sold

In [64]:
print(units_sold.sum(axis=0))

[ 485 1950 1240  345  980  720]


Management Recommendations

1.Best-performing store

In [65]:
print(np.max(sales_data))

1050000


2.Lowest-Performing store

In [66]:
print(np.min(sales_data))

175000


3.Most Profitable category

In [75]:
result=np.max(profit_data.sum(axis=1))
print(result)

755000


4.Lowest-Profit Category

In [76]:
result=np.min(profit_data.sum(axis=1))
print(result)

505000


5.Store recommended for expansion

In [79]:
total_store_profit = np.sum(profit_data, axis=1)
best_store_index = np.argmax(total_store_profit)
print("Store Recommended for Expansion:", stores[best_store_index])


Store Recommended for Expansion: Mumbai


6.Category requiring additional marketing

In [82]:
result=(np.argmin(sales_data.sum(axis=0)))
print(categories[result])

Beauty


7.Store-category combinations needing cost optimization

In [83]:
print(np.max(cost_data))

790000


8.Store-category combinations requiring inventory reorder

In [84]:
result=np.where(closing_Stock < 25)
print(result)

(array([4]), array([3]))
